spring:
  cloud:
    function:
      definition: pack|label
    stream:
      bindings:
        packlabel-in-0:
          destination: order-accepted
          group: book-dispatcher
        packlabel-out-0:
          destination: order-dispatched
  rabbitmq:
    host: 35.192.18.170
    port: 5672
    username: test
    password: test
    connection-timeout: 15s
